# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-alpine

# Set working directory
WORKDIR /app

# Install build dependencies
RUN apk add --no-cache gcc musl-dev linux-headers

# Copy requirements and project files
COPY pyproject.toml ./
COPY requirements.txt ./
COPY README.md ./
COPY src/ ./src/
COPY uv.lock ./

# Install pipenv system dependencies
# Install project dependencies using pip
RUN pip install --upgrade pip \
    && pip install --ignore-installed -r requirements.txt || true

# Install project using Hatchling build
RUN pip install hatchling \
    && pip install .

# Expose any port if needed (not strictly needed for stdio based server)

CMD ["python", "src/server/server.py"]
