# Client types
CLIENT_CLAUDE_DESKTOP = "claude-desktop"
CLIENT_CLAUDE_CODE = "claude-code"
CLIENT_CURSOR = "cursor"
CLIENT_VSCODE = "vscode"
CLIENT_VSCODE_INSIDERS = "vscode-insiders"
CLIENT_WINDSURF = "windsurf"
CLIENT_LM_STUDIO = "lm-studio"
CLIENT_GEMINI = "gemini"

# Transport types
TRANSPORT_STDIO = "stdio"
# TRANSPORT_SSE = "sse"
# TRANSPORT_STREAMABLE_HTTP = "streamable-http"

# Choices for Click options
CLIENT_CHOICES = [
    CLIENT_CLAUDE_DESKTOP,
    CLIENT_CLAUDE_CODE,
    CLIENT_CURSOR,
    CLIENT_VSCODE,
    CLIENT_VSCODE_INSIDERS,
    CLIENT_WINDSURF,
    CLIENT_LM_STUDIO,
    CLIENT_GEMINI,
]
TRANSPORT_CHOICES = [TRANSPORT_STDIO]

# Defaults
DEFAULT_CLIENT = CLIENT_CLAUDE_DESKTOP
DEFAULT_TRANSPORT = TRANSPORT_STDIO
