# Client types
CLIENT_CLAUDE = "claude"
CLIENT_CURSOR = "cursor"

# Transport types
TRANSPORT_STDIO = "stdio"
# TRANSPORT_SSE = "sse"
# TRANSPORT_STREAMABLE_HTTP = "streamable-http"

# Choices for Click options
CLIENT_CHOICES = [CLIENT_CLAUDE, CLIENT_CURSOR]
TRANSPORT_CHOICES = [TRANSPORT_STDIO]

# Defaults
DEFAULT_CLIENT = CLIENT_CLAUDE
DEFAULT_TRANSPORT = TRANSPORT_STDIO
